### ISSUE TITLE
Error accessing questions.

### ISSUE THREAD

**Issue by iostreamz** [splunk/SA-ctf_scoreboard#10]
When accessing the questions as a competitor I am receiving the error message below despite following all instructions to the letter. 

UnboundLocalError at "/opt/splunk/etc/apps/SA-ctf_scoreboard/bin/gethints.py", line 121 : local variable 'ctf_hints' referenced before assignment

**Comment by daveherrald** [comment]
Good find. You are correct, no need to quote the strings right of the equal sign in that file.
