### ISSUE TITLE
Where to find sample questions and answers

### ISSUE THREAD

**Issue by bcyates** [splunk/SA-ctf_scoreboard#13]
The instructions say to "Obtain the following three files: ctf_questions.csv, ctf_answers.csv, ctf_hints.csv" 

But it does not tell us where to obtain the files. The links in the blog post just bring us back to the GIT. Not sure where to find those files.

**Comment by dickens88** [comment]
I got the same issue ...

**Comment by daveherrald** [comment]
Hey all. Send an email to bots at splunk dot com and we will send you the files!

**Comment by dickens88** [comment]
@daveherrald thank you so much man!
