### ISSUE TITLE
404 When submitting answers

### ISSUE THREAD

**Issue by annoyingapt** [splunk/SA-ctf_scoreboard#21]
Hey all,

Can't seem to figure this one out. Everything else seems to work, but I get a 404 Not Found when submitting an answer, even with the sample data. Do you have any suggestions for things to check?

**Comment by daveherrald** [comment]
@annoyingapt Can you provide a screenshot and the contents of $SPLUNK_HOME/var/log/scoreboard/scoreboard_admin.log

**Comment by annoyingapt** [comment]
My scoreboard_admin.log file is empty. It is most likely something I have done, but if there is anything I can try before starting from scratch would be great.

`root@dashboard:/opt/splunk/var/log/scoreboard# ls -sl
total 0
0 -rw------- 1 root root 0 Mar 15 20:27 scoreboard_admin.log`

URL:
`https://127.0.0.1:8000/en-US/custom/SA-ctf_scoreboard/scoreboard_controller/submit_question?Number=1&Question=This+is+a+simple+question+to+get+you+familiar+with+submitting+answers.+What+is+the+name+of+the+company+that+makes+the+software+that+you+are+using+for+this+competition%3F+Just+a+six-letter+word+with+no+punctuation.&Answer=Splunk`

![screenshot](https://user-images.githubusercontent.com/55898651/76798981-8f013d80-6835-11ea-83de-be5e2e2c3405.png)

**Comment by J4son** [comment]
May be your splunk enterprise version is 8.0 . Seems that v8.0 doesn't work well with scoreboard. You can try v7.3.

**Comment by aspina** [comment]
J4Son is correct, I made the same mistake and immediately installed on 8.0.
7.3.2 will work best (despite the docs saying 7.1.x is tested)....Also, make sure the "apps" you add match the versions on the readme.

**Comment by frake3** [comment]
Confirmed this issue as well. Worked fine on 7.3.5

**Comment by daveherrald** [comment]
v7.3.x is probably the best choice at this time. Has not been tested on v8.

**Comment by annoyingapt** [comment]
Sorry for the delay, I'll give 7.3.5 a go today and confirm.

**Comment by fbys294** [comment]
I ran into this as well, I downgraded to 7.3.5, the problem still was their. I then found a solution online. Can't remember the website but: vim /opt/splunk/etc/apps/Splunk_TA_microsoft-cloudservices/bin/splunktamscs/ca_certs_locater.py 
Change the TEMP_CERT_FILE_PATH from None to  TEMP_CERT_FILE_PATH = '/etc/pki/tls/certs/ca-bundle.crt'
Now restart splunk and try to submit a answer.

**Comment by annoyingapt** [comment]
Hey guys, sorry I never got this going. I gave up in the end and just hosted a CTFd instance.
