### ISSUE TITLE
Deduct Hints Only After Correct Answer

### ISSUE THREAD

**Issue by pyrodie18** [splunk/SA-ctf_scoreboard#3]
Would suggest that there be an option (or default setting) that deducts the points only after the user has entered the correct answer for the question instead of as soon as they receive the hint.

**Comment by pyrodie18** [comment]
Don't know that I would say it's important, just that its a nice feature to have.  I was hosting a CTF (not Splunk related but more traditional cyber stuff) last year and one of the comments I got from the players afterwards was some frustration that they had lost points to get the hint, but still hadn't been able to solve the problem to recoup some of those points.  Of course this was using the Facebook CTF engine which only allowed a single hint so it was either make it a semi useful hint or basically give the answer.  With BOTS at least I'm able to include multiple hints at various costs giving more and more information.  Either way, just an idea.

**Comment by daveherrald** [comment]
This is not something we at Splunk are going to pursue, but feel free to propose implementation ideas.
