### ISSUE TITLE
Include Clustering Instructions

### ISSUE THREAD

**Issue by pyrodie18** [splunk/SA-ctf_scoreboard#4]
I'm pretty sure you guys are clustering the SHs when you host this which I tried to do last night without a lot of luck (of course I was tired so I was pretty well useless).  Would be nice to include instructions or at least a comment that indicates how exactly you are clustering if the competition is big enough.  I plan on playing with this this weekend and will submit a pull request if I get it working unless you beat me to it.

**Comment by daveherrald** [comment]
We don't cluster the search heads for our events. KISS :-)
