### ISSUE TITLE
NoSectionError / TypeError

### ISSUE THREAD

**Issue by MMoermans** [splunk/SA-ctf_scoreboard#9]
Hi there,

I'm trying to set up the Boss of the SOC v1 (BOTS) environment but I keep getting the following error while looking at the questions page in the app. I've followed all the steps in the guide (https://github.com/splunk/SA-ctf_scoreboard) so I'm confused why I keep getting this error:

     NoSectionError at "/opt/splunk/lib/python2.7/ConfigParser.py", line 607 : No section: 'ScoreboardController'
     
      TypeError at "/opt/splunk/lib/python2.7/json/decoder.py", line 364 : expected string or buffer

Does anyone know what might cause this error?

**Comment by daveherrald** [comment]
What does your $SPLUNK_HOME/etc/apps/SA-ctf_scoreboard/appserver/controllers/scoreboard_controller.config look like?

**Comment by MMoermans** [comment]
The issue was due to the app having the name SA-ctf_scoreboard-master instead of SA-ctf_scoreboard, changing that the error was resolved.

I now have the following error even though the ctf_hints was properly imported:

`UnboundLocalError at "/opt/splunk/etc/apps/SA-ctf_scoreboard/bin/gethints.py", line 121 : local variable 'ctf_hints' referenced before assignment`

**Comment by MMoermans** [comment]
Figured it out, since we had a different default port the python scripts used needed to be adjusted.
